
# Use the official Node.js image
FROM node:14

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY ./project/frontend/src/package*.json ./
RUN npm install

# Copy app source code
COPY ./project/frontend/src/ .

# Expose port 8080
EXPOSE 8080

# Serve the app
CMD [ "npm", "run", "serve" ]
