
# Use the official PHP image
FROM php:7.4-apache

# Copy application source code to the Apache document root
COPY ./project/backend/src/ /var/www/html/

# Enable Apache mod_rewrite
RUN a2enmod rewrite

# Install mysqli PHP extension
RUN docker-php-ext-install mysqli

# Expose port 80
EXPOSE 80
